- id: doi:10.1101/2025.10.05.680545
  type: paper
  description: R package to create in-house LC-MS/MS libraries.
  image: https://github.com/CooperstoneLab/MS2extract/blob/main/man/figures/MS2extract_logo.png?raw=true
  buttons:
    - type: source
      link: https://github.com/CooperstoneLab/MS2extract
    - type: website
      link: https://www.cooperstonelab.com/MS2extract/
  tags:
    - Mass spectrometry
    - Metabolomics
    - R package
  repo: CooperstoneLab/MS2extract

- id: doi:10.70099/BJ/2024.01.02.4
  type: paper
  description: Evaluation of antagnism between Pseudovibrio denitrificans and Vibrio parahaemolyticus.
  image: https://bionaturajournal.com/images/2024.01.02.4-Figure-2.jpg
  buttons:
    - type: website
      link: https://bionaturajournal.com/2024.01.02.4.html
  tags:
    - Mass spectrometry
    - Metabolomics

- id: doi:10.1186/s12870-024-04854-7
  type: paper
  description: Transcriptomic and metabolomic analyses reveal the role of exogenous
    abscisic acid in promoting drought resistance in poplar.
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12870-024-04854-7/MediaObjects/12870_2024_4854_Fig5_HTML.png?as=webp
  buttons:
    - type: website
      link: https://bmcplantbiol.biomedcentral.com/articles/10.1186/s12870-024-04854-7
  tags:
    - Microbiome
    - Bioinformatics
    - Metagenomics

- id: doi:10.2166/wh.2024.290
  type: paper
  description: Microbiome assesment in drinking water systems in Ecuador using metagenomics.
  image: https://iwa.silverchair-cdn.com/iwa/content_public/journal/jwh/22/3/10.2166_wh.2024.290/1/jwh-d-23-00290gf01.png?Expires=1763858864&Signature=PwXlnR6TNopuhMuZvQF1FhjWdhj1ArWo46W6ZvrMdLVwulHoT~3NtCQi~hG0Js2JHV-jvhM3RW7ilU72hKnXXVbd3pcQ-Bcs0AzI0F61Uoxd0-QLNmniEhyeUypie1Xh9FQ6Zca4YSxN6qXGC2SvNFKWWmAuPQQf5E7SJKzxoKWR5zpsR5oH14epvtI2Ur-5uDGsHquQZEtntGeaKw-8MqOR1IRcBJMkivL2oXSNszP7kSOH9jRtZKyqvK9EuX5CMdNZHhYTcVxx~gvyC19vJRsA9Prk1Jo9pGwYyxLeI5fFREzMUc17DKtX7mWcvlomz8rw9IRTHkj6Mf32H0VEcg__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  buttons:
    - type: website
      link: https://iwaponline.com/wh/article/22/4/590/95496/Metabolomic-profiling-and-toxicity-assessment-of
  tags:
    - Metagenomics
    - Bioinformatics