- id: doi:10.1101/2025.10.05.680545
  type: paper
  description: R package to create in-house LC-MS/MS libraries.
  image: https://github.com/CooperstoneLab/MS2extract/blob/main/man/figures/MS2extract_logo.png?raw=true
  buttons:
    - type: source
      link: https://github.com/CooperstoneLab/MS2extract
    - type: website
      link: https://www.cooperstonelab.com/MS2extract/
  tags:
    - Mass spectrometry
    - Metabolomics
    - R package
  repo: CooperstoneLab/MS2extract

- id: doi:10.70099/BJ/2024.01.02.4
  type: paper
  description: Evaluation of antagnism between Pseudovibrio denitrificans and Vibrio parahaemolyticus.
  image: https://bionaturajournal.com/images/2024.01.02.4-Figure-2.jpg
  buttons:
    - type: website
      link: https://bionaturajournal.com/2024.01.02.4.html
  tags:
    - Mass spectrometry
    - Metabolomics

- id: doi:10.1186/s12870-024-04854-7
  type: paper
  description: Transcriptomic and metabolomic analyses reveal the role of exogenous
    abscisic acid in promoting drought resistance in poplar.
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12870-024-04854-7/MediaObjects/12870_2024_4854_Fig5_HTML.png?as=webp
  buttons:
    - type: website
      link: https://bmcplantbiol.biomedcentral.com/articles/10.1186/s12870-024-04854-7
  tags:
    - Microbiome
    - Bioinformatics
    - Metagenomics

- id: doi:10.2166/wh.2024.290
  type: paper
  description: Microbiome assesment in drinking water systems in Ecuador using metagenomics.
  image: https://iwaponline.com/view-large/figure/3626729/jwh-d-23-00290f02.tif
  buttons:
    - type: website
      link: https://iwaponline.com/wh/article/22/4/590/95496/Metabolomic-profiling-and-toxicity-assessment-of
  tags:
    - Metagenomics
    - Bioinformatics

- id: doi:10.1128/spectrum.02506-22
  type: paper
  description: effects of tomato consumption on the gut microbiome, as tomatoes account for 22% of vegetable consumption in Western diets
  image: https://journals.asm.org/cms/10.1128/spectrum.02506-22/asset/43efd38b-8ea0-448e-bcf6-b8c9a6a6f29c/assets/images/medium/spectrum.02506-22-f001.gif
  buttons:
    - type: website
      link: https://journals.asm.org/doi/10.1128/spectrum.02506-22
  tags:
    - Metabolomics
    - Mass spectrometry
    - Microbiome