- id: doi:10.1101/2025.10.05.680545
  type: paper
  description: MS2extract is an R package designed to facilitate the creation of LC-MS/MS
  image: https://github.com/CooperstoneLab/MS2extract/blob/main/man/figures/MS2extract_logo.png?raw=true
  buttons:
    - type: source
      link: https://github.com/CooperstoneLab/MS2extract
    - type: website
      link: https://www.cooperstonelab.com/MS2extract/
  tags:
    - mass spectrometry
    - metabolomics
    - R package
  repo: CooperstoneLab/MS2extract